using UnityEngine;
using System.Collections;

public class BoardController : MonoBehaviour {

    Vector3[,] vectors = new Vector3[15,15] {
        {
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },
        {
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },{
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
            new Vector3(1,9),
        },
    };

    static Object[,] grid = new Object[15, 15];
    public GameObject[] hexagons;

	public bool AddHex ( int xpos, int ypos, int color ) {

        if ( grid[ xpos, ypos ] == null )
        {

            grid[ xpos, ypos ] = Instantiate( hexagons[ color ], vectors[ xpos, ypos ], Quaternion.identity );

            return true;

        }
        else
        {

            return false;

        }

	}

}
